# Generated by Django 5.0.3 on 2024-08-12 13:56

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_userprofile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="+93707323964", max_length=128, region=None
            ),
            preserve_default=False,
        ),
    ]
